### ISSUE TITLE
Max file size, maximum number of files and error handling

### ISSUE THREAD

**Issue by simkepal** [bleenco/ngx-uploader#123]
Hello,

Great service! 
I have three questions.
Is it possible to allow only files, that are smaller than 5MB?
Can you limit number of files? So that user can upload only 5 images?
What if api server returns an error? How can be this handled?

Thank you for your help!

Best regards!

**Comment by lukasz-galka** [comment]
**Is it possible to allow only files, that are smaller than 5MB?**
you can use "maxSize" option and handle this in onUploadRejected event

html
`<input type="file" ngFileSelect [(options)]="options" (onUploadRejected)="handleReject($event)"> `

ts
```
ngOnInit() {
    this.options = { maxSize: 1000 };
}

handleReject(status: UploadRejected): void {
    if(status && status.reason === 'MaxSizeExceeded') {
        // your code
    }
}
```

**Can you limit number of files? So that user can upload only 5 images?**
there is an option "maxUploads" but is not working, for this you can make something like this

html
`<input type="file" ngFileSelect [(options)]="options" [events]="startUploadEvent" (change)="handleChange($event)">`

ts
```
startUploadEvent: EventEmitter<string> = new EventEmitter<string>();

ngOnInit() {
    this.options = { autoUpload: false, maxUploads: 10 };
}

handleChange(event: Event) {
    if((<HTMLInputElement>event.target).files.length <= this.options.maxUploads)) {
        this.startUploadEvent.emit('startUpload');
    } else {
        // show error/info
    }
}
```

I am setting auto upload to false and checking selected files count in "change" event

**What if api server returns an error? How can be this handled?**

html
`<input type="file" ngFileSelect [(options)]="options" (onUpload)="handleUpload($event)">`

ts
```
handleUpload(data: any): void {
    if (data && data.response === '') {
        // error
    } else if (data && data.response) {
        // success
    }
}

```

**Comment by bougsid** [comment]
I need to handle errors returned and I try this solution but unfortunately  doesn't work for me, `handleUpload(data : any) ` does not getting called.

I tried to debug your component and I didn't find any place where you fire` (onUpload)` event.

Hope there is a solution, I struggle with this for more than 2 days

**Comment by TonyLuo** [comment]
@lukasz-galka I try to  limit number of files, but seems it doesn't work
```
<input type="file" ngFileSelect [(options)]="options" [events]="startUploadEvent" (change)="handleChange($event)">

Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'input'. ("(change)="handleChange($event)"
             (onUploadRejected)="handleReject($event)"
             [ERROR ->][(options)]="options" [events]="startUploadEvent"
             multiple>
```

**Comment by TonyLuo** [comment]
seems there is no UploadRejected class any more

**Comment by lukasz-galka** [comment]
@TonyLuo my solution was for version 2.x, unfortunately I am not familiar with version 3.x

**Comment by sharmaprashant232** [comment]
@lukasz-galka I didn't find maxSize, maxUploads in options type of UploaderOptions. Can you help me with this?

**Comment by retailify** [comment]
@lukasz-galka the current release does'nt restrict the maxSize or maxUploads. It's on the roadmap, but I'm really busy at the moment...

**Comment by maximelafarie** [comment]
Anything new with `maxSize` option?
