### ISSUE TITLE
Demo is broken - Can't bind to 'options'.  SetTimeOut() doesn't compile

### ISSUE THREAD

**Issue by stuman93** [bleenco/ngx-uploader#232]
Demo is not working.  I'm using angular-cli.  I followed all of the instructions on the demo.  What is up with all of the demos for Angular2? They are all broken.  Yours, ng-upload by Valor software.  Even the stackoverflow's nice example referenced [here](http://stackoverflow.com/questions/40214772/file-upload-in-angular-2) is broken as well.  Is there something wrong with my angular-cli?  I can't get not one example on the web regarding angular2 and fileuploads to work.  Please help!  I'm using the vanilla out-of-box CLI provided on the Angular2's website.

Here is the response from Chrome:
Can't bind to 'options' since it isn't a known property of 'div'. ("<div class="drag-n-drop-container"
      ngFileDrop
      [ERROR ->][options]="options"
      (onUpload)="handleUpload($event)"
      [ngClass]="{'file-over': hasBaseDro"): NgxUploaderComponent@2:6
Can't bind to 'options' since it isn't a known property of 'input'. ("
           class="hidden"
           ngFileSelect
           [ERROR ->][options]="options"
           (onUpload)="handleUpload($event)">
    Browse
"): NgxUploaderComponent@11:11 ; Zone: <root> ; Task: Promise.then ; Value:

**Comment by zegilooo** [comment]
I got the same error
`Unhandled Promise rejection: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'div'. ("<div class="drag-n-drop-container"
      ngFileDrop
      [ERROR ->][options]="options"
      (onUpload)="handleUpload($event)"
      [ngClass]="{'file-over': hasBaseDro"): AppComponent@2:6
Can't bind to 'options' since it isn't a known property of 'input'. ("
           class="hidden"
           ngFileSelect
           [ERROR ->][options]="options"
           (onUpload)="handleUpload($event)">
    Browse
"): AppComponent@11:11 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'div'. ("<d…, _nativeError: ZoneAwareError, __zone_symbol__currentTask: ZoneTask, __zone_symbol__stack: "Error: Template parse errors:↵Can't bind to 'optio…ttp://localhost:4200/polyfills.bundle.js:6423:35)", __zone_symbol__message: "Template parse errors:↵Can't bind to 'options' sin…pload($event)">↵    Browse↵"): AppComponent@11:11"} Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'div'. ("<div class="drag-n-drop-container"
      ngFileDrop
      [ERROR ->][options]="options"
      (onUpload)="handleUpload($event)"
      [ngClass]="{'file-over': hasBaseDro"): AppComponent@2:6
Can't bind to 'options' since it isn't a known property of 'input'. ("
           class="hidden"
           ngFileSelect
           [ERROR ->][options]="options"
           (onUpload)="handleUpload($event)">
    Browse
"): AppComponent@11:11
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:6869:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:64389:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:5723:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:17589:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:47585:68)
    at http://localhost:4200/vendor.bundle.js:47468:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:47468:19)
    at createResult (http://localhost:4200/vendor.bundle.js:47350:19)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6211:26)
    at Zone.run (http://localhost:4200/polyfills.bundle.js:6003:43)
    at http://localhost:4200/polyfills.bundle.js:6590:57
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6244:31)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6043:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6423:35)
consoleError @ zone.js:522
handleUnhandledRejection @ zone.js:527
_loop_1 @ zone.js:562
drainMicroTaskQueue @ zone.js:566
`

**Comment by byronsliger** [comment]
me too

**Comment by zerefel** [comment]
Hey guys, I had the same issue in Angular 2, and I solved it by importing the **NgUploaderModule** in the parent module, and not the grandparent module _(relative to the module where I wanted to use the functionality of the file uploader)_.

My structure is as follows:

├ GrandparentModule - _do not import here_
├── ParentModule  - _add to imports here_
 │----├── TargetModule - _directives accessible here_

**Comment by rafaelss95** [comment]
@zerefel solution worked for me.

**Comment by largeDachshund** [comment]
@zerefel's solution worked for me, too.

**Comment by oleosjo** [comment]
I still have this issue, @zerefel's solution didn't work for me. Anyone else have this problem?
