### ISSUE TITLE
Error: Has no exported member 'PLATFORM_ID'. and isPlatformServer'

### ISSUE THREAD

**Issue by lucasratske** [bleenco/ngx-uploader#267]
I am getting this error:
`ERROR in C:/../node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-drop.directive.ts (1,81): Module '"C:/../node_modules/@angular/core/index"' has no exported member 'PLATFORM_ID'.

ERROR in C:/../node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-drop.directive.ts (2,10): Module '"C:/../node_modules/@angular/common/index"' has no exported member 'isPlatformServer'.`

Anyone has the solution?

**Comment by jkuri** [comment]
upgrading Angular version should be enough.

**Comment by Waldspecht** [comment]
I'm having the same issue. I'm currently using Angular Version 2.4.5.
@lucasratske: Have you  solved your issue?
Any suggestions?
Thanks in advance and best regards.

**Comment by jkuri** [comment]
hi @Waldspecht, problem is because `@angular/common` does not export PLATFORM_ID which is exported by Angular 4 and forward versions. 
I am using that for checking if this is used by server-side prerendering and currently this cannot work on Angular versions 2.x.x. Did you try to upgrade your project's Angular version?

**Comment by Waldspecht** [comment]
Thanks for your quick response. I now have managed to update my App to Angular 4... was a real pain and now everything works. Thanks again!

**Comment by jkuri** [comment]
glad you got it working. i think upgrading to 4 is a win-win.
