### ISSUE TITLE
PHP backend example

### ISSUE THREAD

**Issue by taat** [bleenco/ngx-uploader#404]
Why the PHP example was removed?

I have found some dead links pointing to:
https://github.com/bleenco/ngx-uploader#backend-example-using-plain-php

How the PHP backend should look like?
Could you show some JSON responses at least?

Is this a streamed version or multipart? How the memory limits are managed for big files (eg. 1GB)?

**Comment by retailify** [comment]
Hi @taat, I'm not a php guy at all and I'm since 4.x onboard. So I can't answer the question, why the example was removed. But I think, it's version related.

ngx-uploader uploads the files as multipart upload. 

For the php part, look at [W3Schools](https://www.w3schools.com/php/php_file_upload.asp) or ask your question on [Stack Overflow](https://stackoverflow.com)
