### ISSUE TITLE
Sass styling required

### ISSUE THREAD

**Issue by c-martinez** [bleenco/ngx-uploader#412]
I tried to use ngx-uploader but when I create a drop-container as in [the example](https://github.com/bleenco/ngx-uploader#example), the resulting component does not have the same styling as [on the demo](http://ngx-uploader.com/).

To get the styling to work, I've added the styleUrl to my component:

```
@Component({
  ...
  styleUrls: ['./node_modules/ngx-uploader/src/styles/app.sass']
})
```
and had to manually install bulma: `yarn add bulma`, then it seems to be working.

Is this something which should happen automatically? Did I miss a step somewhere and it didn't happen automatically only for me? Or should it perhaps be documented somewhere?

**Comment by jkuri** [comment]
hi @c-martinez,
[bulma](https://github.com/bleenco/ngx-uploader/blob/master/package.json#L52) is pretty much added to the dependencies and it serves only for demo purposes. This module isn't about css styling or any other design features rather than just showing how make the upload work.
Included demo serves only for the demo website.

**Comment by c-martinez** [comment]
hi @jkuri ,

Thanks for clarifying this. I'll close this issue then.
